### PR TITLE
fix: check if event status was changed to cancelled and generate appr…

### PR DESCRIPTION
**Pull request by SebastianKrupinski**
fix: check if event status was changed to cancelled and generate appropriate message

### CODE REVIEW

**Comment by phil-davis** [comment]
Thanks for the contribution.
@SebastianKrupinski php-cs-fixer fails because of the new version 3.64.
I have fixed the code-style in PR #672
Please rebase, and add a test to cover the new behavior.

**Comment by SebastianKrupinski** [comment]
> Thanks for the contribution. @SebastianKrupinski php-cs-fixer fails because of the new version 3.64. I have fixed the code-style in PR #672 Please rebase, and add a test to cover the new behavior.

Done

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
Backported to the 4.5 branch in PR #695

**Comment by phil-davis** [comment]
Released in https://github.com/sabre-io/vobject/releases/tag/4.5.6

**Pull request merged**
