### PR TITLE
Fix possible infinite loop in RRuleIterator.php

### PR DESCRIPTION
**Pull request by mvdnes**
When the RRule FREQ is YEARLY and it uses BYYEARDAY only, an infinite loop could occur.
$this->currentDate may be an DateTimeImmutable, so a reassignment is necessary.

### CODE REVIEW

**Comment by staabm** [comment]
Could you provide a unit test which fails without the patch?

**Comment by mvdnes** [comment]
I have added a test.

**Comment by DominikTo** [comment]
Without the change, the new test indeed runs into an infinite loop.

**Comment by mvdnes** [comment]
Is there any timeline on when this will be merged?

**Comment by staabm** [comment]
@mvdnes
Did you run into this problem because a particular client issued a request like that?

Or did you find the problem by studying the codebase and thinking about possible edge cases?

**Comment by staabm** [comment]
@ any maintainer: I dont have enough domain knowledge about this context.

Anyone more in this topic then me: feel free to merge in case this is issue worth beeing fixed

**Comment by mvdnes** [comment]
I think this particular event was imported from an export of my Google calendar. I found the fix by studying (and modifying) the codebase.

**Comment by staabm** [comment]
@BlacklkeEagle can you confirm this fix works?

**Comment by staabm** [comment]
Do we need the same fix for all other occurences of setDate() etc. On date objects in this class?

**Comment by BlackIkeEagle** [comment]
@staabm Yes I can confirm this fix works

**Comment by BlackIkeEagle** [comment]
@staabm In this file this is the only occurence of setDate, but in other files where you want to be able to use DateTime and DateTimeImmutable in the same way this change should be applied to avoid future issues

**Comment by BlackIkeEagle** [comment]
@staabm every setter used on a DateTime or DateTimeImmutable should be converted in best case to the format of $date = $date->set... to allow DateTime and DateTimeImmutable cross use

**Comment by BlackIkeEagle** [comment]
Could this be merged please, this causes "real life" issues

**Comment by laoneo** [comment]
Actually tested it and it worked. Please merge and ship it. @mvdnes, to get it merged, you probably need to update your branch as github tells me that the branch is out of date.

**Comment by laoneo** [comment]
Thanks!

**Comment by mvdnes** [comment]
Thank you for merging!

**Comment by staabm** [comment]
released 4.1.4
https://github.com/sabre-io/vobject/releases/tag/4.1.4

**Comment by laoneo** [comment]
Nice Christmas present :smile:

**Comment by BlackIkeEagle** [comment]
Thanks for merging this fix

**Pull request merged**
