### PR TITLE
Additional vtimezone validation rules

### PR DESCRIPTION
**Pull request by jpirkey**
see also #418 

Reference: https://www.kanzaki.com/docs/ical/vtimezone.html

### CODE REVIEW

**Comment by jpirkey** [comment]
Two tests still fail, but I'd like some input as to if that is truly expected behavior and we need to support that or not:
image

**Comment by jpirkey** [comment]
@evert can you give me an idea who the new maintainers are?  They seem to be less responsive then you ;-)

**Comment by renaudboyer** [comment]
ICal test is failing because the following rules cannot work with VTimezone validation rules: 
```
'DTSTART' => 1,
'TZOFFSETTO' => 1,
'TZOFFSETFROM' => 1,
```
They are are correct within `DAYLIGHT` and `STANDARD` but not in `TIMEZONE` as `DAYLIGHT` and `STANDARD` are `0+`
With the way VTimezone work, rules should be:
```
'DTSTART' => '*',
'TZOFFSETTO' => '*',
'TZOFFSETFROM' => '*',
```

**Comment by jpirkey** [comment]
Riiiight.  I see that now.  Thanks!

**Comment by renaudboyer** [comment]
I Agree and as '*' means no verification, I think we should not add them.

**Pull request closed without merging**
