### PR TITLE
Test with php 7.3

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@staabm seems like there is no way to test with the current travis config on php 5.5

I vote for removing php 5.5 from travis for now - later we can decide to drop it completly ...

Objections?

**Comment by evert** [comment]
Why don't you cut a new major version and drop PHP < 7? Might make your life a bit easier.

**Comment by DeepDiver1975** [comment]
We can drop older version in a followup pr.

@staabm merge? We can then tag a new alpha and setup dependencies in other repos properly.

**Comment by staabm** [comment]
Thanks

**Comment by staabm** [comment]
4.2.0. when we dont drop php5, agree

**Comment by DeepDiver1975** [comment]
here we go - https://github.com/sabre-io/vobject/releases/tag/4.2.0-alpha1

**Pull request merged**
