### PR TITLE
[tests-only] Explicitly select PHP 8.0 in CI

### PR DESCRIPTION
**Pull request by phil-davis**
see if Travis understands this today :) 

https://www.php.net/releases/8.0/en.php

### CODE REVIEW

**Comment by phil-davis** [comment]
https://www.traviscistatus.com/#week

This stuff needs to be done at weekends. Travis has a continuous queue of open-source jobs all week.

**Comment by phil-davis** [comment]
https://travis-ci.org/github/sabre-io/vobject/jobs/746192874
```
$ phpenv global 8.0 2>/dev/null

8.0 is not pre-installed; installing

Downloading archive: https://storage.googleapis.com/travis-ci-language-archives/php/binaries/ubuntu/20.04/x86_64/php-8.0.tar.bz2

0.07s$ curl -sSf --retry 5 -o archive.tar.bz2 $archive_url && tar xjf archive.tar.bz2 --directory /

curl: (22) The requested URL returned error: 404 

0.00s0.01s$ phpenv global 8.0

rbenv: version `8.0' not installed

The command "phpenv global 8.0" failed and exited with 1 during .
```

Too soon!

**Comment by staabm** [comment]
In all of my OSS project where we do continous work we moved to github because travis got realy bad build times lately. 

We saw 30-40min faster builds on github actions. 

Might be worth to move on

**Comment by phil-davis** [comment]
close for now. I can play at the weekend, maybe.

**Pull request closed without merging**
