### PR TITLE
Always run phpstan in travis

### PR DESCRIPTION
**Pull request by JeroenVanOort**
I think it would be better if phpstan is always ran for every php version.

### CODE REVIEW

**Comment by staabm** [comment]
Do you have a case in mind which requires running it on all versions?

**Comment by JeroenVanOort** [comment]
Based on the PHP version, different versions of dependencies may be used, which may or may not be compatible with project code. Static analysis seems to be a low-effort/high-gain tool to prevent issues.

In practice, however, phpstan is not compatible with 5.x, so it won't really work for now. It would work when support for these versions is dropped, as you suggested for 4.3. Would it be possible to open a branch for that version? So work can be done without bothering work for 4.2.*.

**Comment by staabm** [comment]
You could just activate phpstan in the builds in which it works with `env: RUN_PHPSTAN="TRUE"`

**Comment by staabm** [comment]
Thx

**Pull request merged**
