### PR TITLE
DTSTAMP must be specified in UTC

### PR DESCRIPTION
**Pull request by Tragen**
DTSTAMP must be specified in UTC
See https://www.kanzaki.com/docs/ical/dtstamp.html

### CODE REVIEW

**Comment by staabm** [comment]
I am wondering, that we dont need to adjust a testcase. I guess this method is not covered.

@Tragen would you mind adding a testcase? dont worry if you dont feel confident enought to do it though.

**Comment by DeepDiver1975** [comment]
> I am wondering, that we dont need to adjust a testcase. I guess this method is not covered.

php env has timezone set to utc? In this case this change would have no impact - right?

**Comment by evert** [comment]
You can't assume the timezone is set to UTC though. It's highly recommended but often not true.

**Comment by DeepDiver1975** [comment]
> You can't assume the timezone is set to UTC though.

sure - my comment was about the fact that tests are passing with this change

**Comment by staabm** [comment]
Ok, no problem. Thx for the PR though

**Pull request merged**
